version: '3.8'

networks:
  app:
    driver: bridge
services:
    webserver:
        image: 'nginx:alpine'
        container_name: "${SERVICE_NAME}_webserver"
        working_dir: /app
        volumes:
            - '.:/app'
            - './infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${NGINX_PORT:-80}:80'
        networks:
            - app
    php-fpm:
        build: 'infrastructure/php-fpm'
        container_name: "${SERVICE_NAME}_source"
        working_dir: /app
        volumes:
            - '.:/app'
            - './infrastructure/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - app
    mysql:
        build: 'infrastructure/mysql'
        container_name: "${SERVICE_NAME}_mysql"
        restart: always
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE:-database_name}"
            MYSQL_USER: "${MYSQL_USER:-database_user}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - '${MYSQL_PORT:-3306}:3306'
        networks:
            - app
    redis:
        image: 'redis:latest'
        container_name: "${SERVICE_NAME}_redis"
        restart: always
        command: redis-server --appendonly yes
        ports:
            - '${REDIS_PORT:-6379}:6379'
        networks:
            - app
        volumes:
            - redis_data:/data

volumes:
    mysql_data:
    redis_data:
